name = "viewora"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages builds into .output/public
pages_build_output_dir = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "viewora-db"
database_id = "75d13564-2ebd-4aa6-a0eb-6bdf6ff79b20"

[[r2_buckets]]
binding = "R2"
bucket_name = "viewora-tours"
